// Note: db import is only used for seed route
// import { db } from '@/lib/db'
export const designEntitiesData = [
  // Design Systems
  {
    id: 'material-design',
    type: 'system',
    name: 'Google Material Design',
    description: 'Одна из самых влиятельных дизайн-систем, созданная для унификации продуктов Google. Включает комплексный набор компонентов, руководств и ресурсов для создания согласованных пользовательских интерфейсов.',
    attributes: JSON.stringify({
      url: 'https://material.io/design',
      components_count: 45,
      features: ['Полный набор компонентов', 'Иконки', 'Кроссплатформенность', 'Руководства по анимации', 'Фокус на доступность', 'Цвета', 'Типографика'],
      color: '#4285f4',
      maintainer: 'Google',
      platforms: ['iOS', 'android', 'Web', 'Flutter'],
      philosophy: 'material metaphor',
      company: 'Google',
    }),
    tags: JSON.stringify(['cross-platform', 'animation', 'android', 'material-you', 'enterprise', 'google', 'accessibility', 'web', 'ios']),
    source: 'DesignSystems from Figma',
    popularity: 98,
    gradient: 'from-blue-500 to-cyan-500',
    techRadarRing: 'adopt',
    techRadarReason: 'Стандарт индустрии, огромная экосистема',
    designRating: 8,
    integrationRating: 10,
    learningRating: 8,
    documentationRating: 10,
    communityRating: 10,
    performanceRating: 9,
    githubStars: '230K',
    npmDownloads: '220M/нед',
    bundleSize: '42 KB',
    bundleSizeBytes: 42000,
    trend: 'stable',
    difficulty: 2,
    recommended: true,
    beginnerFriendly: true,
    maintained: true,
    openSource: true,
  },
  {
    id: 'apple-human-interface-guidelines',
    type: 'system',
    name: 'Apple Human Interface Guidelines',
    description: 'Фундаментальные принципы и правила разработки в экосистеме Apple. Фокусируется на создании интуитивных, элегантных интерфейсов, которые ощущаются нативными для платформ Apple.',
    attributes: JSON.stringify({
      url: 'https://developer.apple.com/design/',
      components_count: 40,
      features: ['Специфика платформы', 'iOS', 'macOS', 'SF Symbols', 'Нативный вид', 'Анимации', 'Элегантный дизайн'],
      color: '#555555',
      maintainer: 'Apple',
      platforms: ['iOS', 'macOS', 'tvOS', 'watchOS', 'visionOS'],
      company: 'Apple',
    }),
    tags: JSON.stringify(['macos', 'native', 'mobile', 'elegance', 'apple', 'ios']),
    source: 'DesignSystems from Figma',
    popularity: 95,
    gradient: 'from-gray-500 to-gray-400',
    techRadarRing: 'adopt',
    techRadarReason: 'Стандарт для Apple экосистемы',
    designRating: 10,
    integrationRating: 9,
    learningRating: 8,
    documentationRating: 10,
    communityRating: 9,
    performanceRating: 10,
    githubStars: 'N/A',
    npmDownloads: 'N/A',
    bundleSize: 'N/A',
    bundleSizeBytes: 0,
    trend: 'stable',
    difficulty: 3,
    recommended: true,
    beginnerFriendly: true,
    maintained: true,
    openSource: false,
  },
  {
    id: 'microsoft-fluent-2',
    type: 'system',
    name: 'Microsoft Fluent 2',
    description: 'Эволюция языка дизайна Microsoft для кроссплатформенных интерфейсов. Подчёркивает гибкость, инклюзивность и восхищение.',
    attributes: JSON.stringify({
      url: 'https://fluent2.microsoft.design',
      components_count: 50,
      features: ['Кроссплатформенность', 'Инклюзивный дизайн', 'Адаптивный макет', 'Свет и глубина'],
      color: '#0078d4',
      maintainer: 'Microsoft',
      platforms: ['Windows', 'Web', 'iOS', 'Android'],
      company: 'Microsoft',
    }),
    tags: JSON.stringify(['microsoft', 'windows', 'copilot', 'inclusivity', 'cross-platform']),
    source: 'design-systems-overview',
    popularity: 85,
    gradient: 'from-cyan-500 to-blue-500',
    techRadarRing: 'adopt',
    techRadarReason: 'Современный дизайн от Microsoft',
    designRating: 8,
    integrationRating: 9,
    learningRating: 7,
    documentationRating: 9,
    communityRating: 8,
    performanceRating: 9,
    githubStars: 'N/A',
    npmDownloads: 'N/A',
    bundleSize: 'N/A',
    bundleSizeBytes: 0,
    trend: 'up',
    difficulty: 3,
    recommended: true,
    beginnerFriendly: true,
    maintained: true,
    openSource: true,
  },
  {
    id: 'ibm-carbon-design',
    type: 'system',
    name: 'IBM Carbon Design',
    description: 'Дизайн-система с открытым исходным кодом для цифровых продуктов. Построена на принципах модульности, доступности и совместной работы.',
    attributes: JSON.stringify({
      url: 'https://carbondesignsystem.com/',
      components_count: 60,
      features: ['Открытый исходный код', 'Модульность', 'Визуализация данных', 'Корпоративная готовность'],
      color: '#0043ce',
      maintainer: 'IBM',
      platforms: ['Web', 'React', 'Vue', 'Angular'],
      company: 'IBM',
    }),
    tags: JSON.stringify(['data-visualization', 'modular', 'react', 'enterprise', 'open-source', 'ibm']),
    source: 'design-systems-overview',
    popularity: 82,
    gradient: 'from-blue-600 to-indigo-700',
    techRadarRing: 'trial',
    techRadarReason: 'Отлично для enterprise',
    designRating: 8,
    integrationRating: 8,
    learningRating: 7,
    documentationRating: 9,
    communityRating: 8,
    performanceRating: 8,
    githubStars: '7K',
    npmDownloads: '200K/нед',
    bundleSize: '100 KB',
    bundleSizeBytes: 100000,
    trend: 'stable',
    difficulty: 3,
    recommended: true,
    beginnerFriendly: false,
    maintained: true,
    openSource: true,
  },
  {
    id: 'shopify-polaris',
    type: 'system',
    name: 'Shopify Polaris',
    description: 'Система дизайна Shopify для создания торговых интерфейсов. Включает компоненты, руководства и ресурсы для электронной коммерции.',
    attributes: JSON.stringify({
      url: 'https://polaris.shopify.com/',
      components_count: 50,
      features: ['Электронная коммерция', 'React-компоненты', 'Руководства по контенту', 'Иконки'],
      color: '#5c6ac4',
      maintainer: 'Shopify',
      platforms: ['Web', 'React', 'iOS', 'Android'],
      company: 'Shopify',
    }),
    tags: JSON.stringify(['e-commerce', 'react-native', 'shopify', 'icons', 'ecommerce', 'react', 'open-source']),
    source: 'design-systems-overview',
    popularity: 80,
    gradient: 'from-indigo-500 to-purple-600',
    techRadarRing: 'trial',
    techRadarReason: 'Лучший выбор для e-commerce',
    designRating: 9,
    integrationRating: 9,
    learningRating: 8,
    documentationRating: 9,
    communityRating: 8,
    performanceRating: 8,
    githubStars: '5K',
    npmDownloads: '300K/нед',
    bundleSize: '80 KB',
    bundleSizeBytes: 80000,
    trend: 'stable',
    difficulty: 2,
    recommended: true,
    beginnerFriendly: true,
    maintained: true,
    openSource: true,
  },
  {
    id: 'atlassian-design-system',
    type: 'system',
    name: 'Atlassian Design System',
    description: 'Система дизайна для продуктов Atlassian (Jira, Confluence, Trello). Обеспечивает единообразие в сложных корпоративных инструментах.',
    attributes: JSON.stringify({
      url: 'https://atlassian.design/',
      components_count: 100,
      features: ['Корпоративные инструменты', 'Богатые компоненты', 'Иконки и иллюстрации', 'Руководства по контенту'],
      maintainer: 'Atlassian',
      platforms: ['Web'],
      company: 'Atlassian',
    }),
    tags: JSON.stringify(['confluence', 'trello', 'atlassian', 'icons', 'enterprise', 'jira']),
    source: 'design-systems-overview',
    popularity: 78,
    gradient: 'from-blue-500 to-indigo-600',
    techRadarRing: 'trial',
    techRadarReason: 'Стандарт для Atlassian продуктов',
    designRating: 8,
    integrationRating: 8,
    learningRating: 7,
    documentationRating: 9,
    communityRating: 8,
    performanceRating: 7,
    githubStars: 'N/A',
    npmDownloads: 'N/A',
    bundleSize: 'N/A',
    bundleSizeBytes: 0,
    trend: 'stable',
    difficulty: 3,
    recommended: false,
    beginnerFriendly: false,
    maintained: true,
    openSource: false,
  },
  // Libraries
  {
    id: 'mantine',
    type: 'library',
    name: 'Mantine UI',
    description: 'Библиотека компонентов для React с фокусом на доступность и отсутствие зависимостей от стилевых фреймворков.',
    attributes: JSON.stringify({
      url: 'https://mantine.dev/',
      components_count: 120,
      hooks_count: 50,
      learning_curve: 'easy',
      customization_level: 'medium',
      setup_time: '10 min',
      frameworks: ['React'],
      features: ['100+ компонентов', 'charts', 'forms', 'Hooks', 'notifications', 'Dates'],
      company: 'Vitaly Rtishchev',
    }),
    tags: JSON.stringify(['admin', 'typescript', 'hooks', 'full-featured', 'react', 'forms', 'dashboard', 'open-source', 'all-in-one', 'accessible', 'components']),
    source: 'DesignSystems from Figma',
    popularity: 92,
    gradient: 'from-orange-500 to-red-500',
    techRadarRing: 'trial',
    techRadarReason: '120+ компонентов, но большой bundle',
    designRating: 9,
    integrationRating: 9,
    learningRating: 8,
    documentationRating: 9,
    communityRating: 8,
    performanceRating: 7,
    githubStars: '26K',
    npmDownloads: '700K/нед',
    bundleSize: '200+ KB',
    bundleSizeBytes: 200000,
    trend: 'up',
    difficulty: 2,
    recommended: true,
    beginnerFriendly: true,
    maintained: true,
    openSource: true,
  },
  {
    id: 'chakra-ui',
    type: 'library',
    name: 'Chakra UI',
    description: 'Модульная и доступная библиотека React-компонентов с встроенной поддержкой темизации и темного режима.',
    attributes: JSON.stringify({
      url: 'https://chakra-ui.com/',
      components_count: 50,
      learning_curve: 'easy',
      customization_level: 'medium',
      setup_time: '15 min',
      frameworks: ['React', 'Vue'],
      features: ['A11y', 'Dark Mode', 'Themeable', 'dark-mode', 'style-props', 'accessibility', 'Composable'],
      company: 'Segun Adebayo',
    }),
    tags: JSON.stringify(['css-in-js', 'open-source', 'modular', 'themeable', 'react', 'accessibility', 'theming', 'developer-experience', 'a11y', 'accessible', 'startup', 'components']),
    source: 'DesignSystems from Figma',
    popularity: 88,
    gradient: 'from-teal-500 to-emerald-500',
    techRadarRing: 'trial',
    techRadarReason: 'Простота использования, но меньше компонентов',
    designRating: 9,
    integrationRating: 9,
    learningRating: 9,
    documentationRating: 9,
    communityRating: 8,
    performanceRating: 7,
    githubStars: '37K',
    npmDownloads: '1.5M/нед',
    bundleSize: '180 KB',
    bundleSizeBytes: 180000,
    trend: 'stable',
    difficulty: 1,
    recommended: true,
    beginnerFriendly: true,
    maintained: true,
    openSource: true,
  },
  {
    id: 'radix-ui',
    type: 'library',
    name: 'Radix UI',
    description: 'Нестилизованные доступные примитивы для React, предоставляющие базовую функциональность без навязанного дизайна.',
    attributes: JSON.stringify({
      url: 'https://www.radix-ui.com/',
      components_count: 30,
      learning_curve: 'hard',
      customization_level: 'high',
      setup_time: '2+ hours',
      frameworks: ['React'],
      features: ['unstyled', 'Composeable', 'headless', 'SSR', 'Accessible', 'Unstyled'],
      company: 'WorkOS',
    }),
    tags: JSON.stringify(['unstyled', 'headless', 'react', 'accessibility', 'open-source', 'a11y', 'accessible', 'primitives', 'components']),
    source: 'DesignSystems from Figma',
    popularity: 95,
    gradient: 'from-violet-500 to-purple-500',
    techRadarRing: 'assess',
    techRadarReason: 'Headless, но нужны свои стили (сложнее для новичков)',
    designRating: 8,
    integrationRating: 10,
    learningRating: 6,
    documentationRating: 9,
    communityRating: 9,
    performanceRating: 10,
    githubStars: '16K',
    npmDownloads: '6M/нед',
    bundleSize: '5-15 KB',
    bundleSizeBytes: 10000,
    trend: 'up',
    difficulty: 4,
    recommended: true,
    beginnerFriendly: false,
    maintained: true,
    openSource: true,
  },
  {
    id: 'shadcn-ui',
    type: 'library',
    name: 'shadcn/ui',
    description: 'Набор переиспользуемых компонентов, скопируйте и вставьте в свой проект. Полный контроль над кодом.',
    attributes: JSON.stringify({
      url: 'https://ui.shadcn.com/',
      components_count: 50,
      learning_curve: 'medium',
      customization_level: 'high',
      setup_time: '30 min',
      frameworks: ['React', 'Next.js'],
      features: ['Не npm пакет', 'Полный контроль', 'Radix UI', 'Tailwind CSS'],
    }),
    tags: JSON.stringify(['radix-ui', 'typescript', 'react', 'tailwind', 'design-system', 'open-source', 'radix', 'copy-paste', 'no-lock-in', 'components']),
    source: 'design-systems-overview',
    popularity: 90,
    gradient: 'from-slate-700 to-slate-900',
    techRadarRing: 'adopt',
    techRadarReason: 'Полный контроль кода, не npm пакет, красивый дизайн',
    designRating: 10,
    integrationRating: 10,
    learningRating: 8,
    documentationRating: 10,
    communityRating: 10,
    performanceRating: 9,
    githubStars: '75K',
    npmDownloads: '3M/нед',
    bundleSize: 'По компонентам',
    bundleSizeBytes: 5000,
    trend: 'up',
    difficulty: 2,
    recommended: true,
    beginnerFriendly: true,
    maintained: true,
    openSource: true,
  },
  {
    id: 'ant-design',
    type: 'library',
    name: 'Ant Design',
    description: 'Корпоративная дизайн-система от Alibaba с богатым набором готовых компонентов для сложных B2B приложений.',
    attributes: JSON.stringify({
      url: 'https://ant.design/',
      components_count: 65,
      learning_curve: 'medium',
      customization_level: 'low',
      setup_time: '20 min',
      frameworks: ['React', 'Vue', 'Angular'],
      features: ['60+ компонентов', 'i18n', 'React', 'charts', 'forms', 'tables', 'Темная тема'],
      company: 'Ant Financial',
    }),
    tags: JSON.stringify(['complex-forms', 'i18n', 'chinese', 'data-tables', 'react', 'alibaba', 'enterprise', 'open-source', 'b2b']),
    source: 'DesignSystems from Figma',
    popularity: 89,
    gradient: 'from-red-500 to-orange-500',
    techRadarRing: 'hold',
    techRadarReason: 'Тяжелый, специфичный для китайского рынка',
    designRating: 7,
    integrationRating: 9,
    learningRating: 7,
    documentationRating: 10,
    communityRating: 9,
    performanceRating: 6,
    githubStars: '93K',
    npmDownloads: '7M/нед',
    bundleSize: '300+ KB',
    bundleSizeBytes: 300000,
    trend: 'stable',
    difficulty: 2,
    recommended: false,
    beginnerFriendly: true,
    maintained: true,
    openSource: true,
  },
  // Technologies - Frontend Frameworks
  {
    id: 'react',
    type: 'technology',
    name: 'React',
    description: 'Библиотека для создания пользовательских интерфейсов от Meta. Самая популярная в мире библиотека для построения UI с компонентным подходом.',
    attributes: JSON.stringify({
      url: 'https://react.dev/',
      version: '19',
      company: 'Meta',
      browserSupport: ['Chrome', 'Firefox', 'Safari', 'Edge', 'IE11*'],
      nodeVersion: '>=16',
      typescript: 'native',
      bestFor: ['SPA', 'Веб-приложения', 'Mobile (React Native)'],
      pros: ['Огромная экосистема', 'Много вакансий', 'React Native'],
      cons: ['Только View', 'Нужны доп. библиотеки'],
    }),
    tags: JSON.stringify(['frontend', 'ui', 'meta', 'spa', 'components', 'hooks', 'jsx']),
    source: 'UI Radar',
    popularity: 98,
    gradient: 'from-cyan-400 to-cyan-600',
    techRadarRing: 'adopt',
    techRadarReason: 'Стандарт индустрии, огромная экосистема, максимум вакансий',
    designRating: 7,
    integrationRating: 10,
    learningRating: 8,
    documentationRating: 10,
    communityRating: 10,
    performanceRating: 9,
    githubStars: '230K',
    npmDownloads: '220M/нед',
    bundleSize: '42 KB',
    bundleSizeBytes: 42000,
    trend: 'stable',
    difficulty: 2,
    recommended: true,
    beginnerFriendly: true,
    maintained: true,
    openSource: true,
  },
  {
    id: 'vue',
    type: 'technology',
    name: 'Vue.js',
    description: 'Прогрессивный JavaScript фреймворк с низким порогом входа и отличной документацией.',
    attributes: JSON.stringify({
      url: 'https://vuejs.org/',
      version: '3',
      company: 'Community',
      browserSupport: ['Chrome', 'Firefox', 'Safari', 'Edge'],
      nodeVersion: '>=16',
      typescript: 'native',
      bestFor: ['SPA', 'PWA', 'Быстрые прототипы'],
      pros: ['Легко учить', 'Отличная документация', 'SFC'],
      cons: ['Меньше вакансий', 'Меньше UI библиотек'],
    }),
    tags: JSON.stringify(['frontend', 'ui', 'sfc', 'spa', 'progressive', 'reactive']),
    source: 'UI Radar',
    popularity: 95,
    gradient: 'from-green-400 to-emerald-600',
    techRadarRing: 'adopt',
    techRadarReason: 'Отличная документация, низкий порог входа, растущее сообщество',
    designRating: 8,
    integrationRating: 9,
    learningRating: 9,
    documentationRating: 10,
    communityRating: 9,
    performanceRating: 9,
    githubStars: '210K',
    npmDownloads: '8M/нед',
    bundleSize: '34 KB',
    bundleSizeBytes: 34000,
    trend: 'up',
    difficulty: 1,
    recommended: true,
    beginnerFriendly: true,
    maintained: true,
    openSource: true,
  },
  {
    id: 'nextjs',
    type: 'technology',
    name: 'Next.js',
    description: 'React фреймворк для продакшена с SSR/SSG. Официальная рекомендация Vercel для production React.',
    attributes: JSON.stringify({
      url: 'https://nextjs.org',
      version: '16',
      company: 'Vercel',
      browserSupport: ['Chrome', 'Firefox', 'Safari', 'Edge'],
      nodeVersion: '>=18',
      typescript: 'native',
      bestFor: ['SSR сайты', 'E-commerce', 'Блоги', 'Корп. сайты'],
      pros: ['SSR/SSG', 'API Routes', 'Оптимизация', 'SEO'],
      cons: ['Vercel-зависимость'],
    }),
    tags: JSON.stringify(['frontend', 'ssr', 'ssg', 'vercel', 'react', 'seo', 'fullstack']),
    source: 'UI Radar',
    popularity: 94,
    gradient: 'from-slate-800 to-slate-900',
    techRadarRing: 'adopt',
    techRadarReason: 'Лучший выбор для SSR/SSG, официальная рекомендация Vercel',
    designRating: 8,
    integrationRating: 10,
    learningRating: 7,
    documentationRating: 10,
    communityRating: 10,
    performanceRating: 10,
    githubStars: '130K',
    npmDownloads: '13M/нед',
    bundleSize: '85 KB',
    bundleSizeBytes: 85000,
    trend: 'up',
    difficulty: 3,
    recommended: true,
    beginnerFriendly: false,
    maintained: true,
    openSource: true,
  },
  {
    id: 'angular',
    type: 'technology',
    name: 'Angular',
    description: 'Платформа для enterprise приложений от Google. Полный фреймворк с DI, routing, forms из коробки.',
    attributes: JSON.stringify({
      url: 'https://angular.dev/',
      version: '18',
      company: 'Google',
      browserSupport: ['Chrome', 'Firefox', 'Safari', 'Edge'],
      nodeVersion: '>=18',
      typescript: 'native',
      bestFor: ['Enterprise', 'Большие команды', 'Банки'],
      pros: ['Полный фреймворк', 'TypeScript native', 'DI'],
      cons: ['Сложно учить', 'Большой bundle'],
    }),
    tags: JSON.stringify(['frontend', 'enterprise', 'google', 'typescript', 'full-framework']),
    source: 'UI Radar',
    popularity: 72,
    gradient: 'from-red-400 to-red-600',
    techRadarRing: 'hold',
    techRadarReason: 'Высокая сложность, большой bundle, специфичный рынок',
    designRating: 7,
    integrationRating: 8,
    learningRating: 5,
    documentationRating: 9,
    communityRating: 9,
    performanceRating: 7,
    githubStars: '96K',
    npmDownloads: '7M/нед',
    bundleSize: '500+ KB',
    bundleSizeBytes: 500000,
    trend: 'stable',
    difficulty: 5,
    recommended: false,
    beginnerFriendly: false,
    maintained: true,
    openSource: true,
  },
  {
    id: 'svelte',
    type: 'technology',
    name: 'Svelte',
    description: 'Компилируемый фреймворк без Virtual DOM. Минимальный bundle и высокая производительность.',
    attributes: JSON.stringify({
      url: 'https://svelte.dev/',
      version: '5',
      company: 'Community',
      browserSupport: ['Chrome', 'Firefox', 'Safari', 'Edge'],
      nodeVersion: '>=16',
      typescript: 'native',
      bestFor: ['Лёгкие приложения', 'Виджеты', 'Быстрые сайты'],
      pros: ['Минимальный bundle', 'Без Virtual DOM', 'Простой синтаксис'],
      cons: ['Меньше экосистема', 'Меньше вакансий'],
    }),
    tags: JSON.stringify(['frontend', 'compiler', 'reactive', 'minimal', 'performance']),
    source: 'UI Radar',
    popularity: 97,
    gradient: 'from-orange-400 to-orange-600',
    techRadarRing: 'trial',
    techRadarReason: 'Инновационный подход, но меньше вакансий',
    designRating: 9,
    integrationRating: 8,
    learningRating: 9,
    documentationRating: 8,
    communityRating: 7,
    performanceRating: 10,
    githubStars: '78K',
    npmDownloads: '3M/нед',
    bundleSize: '1.6 KB',
    bundleSizeBytes: 1600,
    trend: 'up',
    difficulty: 1,
    recommended: true,
    beginnerFriendly: true,
    maintained: true,
    openSource: true,
  },
  {
    id: 'astro',
    type: 'technology',
    name: 'Astro',
    description: 'Фреймворк для контент-сайтов. Zero JS default с Islands Architecture.',
    attributes: JSON.stringify({
      url: 'https://astro.build/',
      version: '5',
      company: 'Community',
      browserSupport: ['Chrome', 'Firefox', 'Safari', 'Edge'],
      nodeVersion: '>=18',
      typescript: 'native',
      bestFor: ['Блоги', 'Документация', 'Маркетинг', 'Портфолио'],
      pros: ['Zero JS default', 'Multi-framework', 'Content collections'],
      cons: ['Не для SPA'],
    }),
    tags: JSON.stringify(['frontend', 'content', 'ssg', 'zero-js', 'islands', 'seo']),
    source: 'UI Radar',
    popularity: 98,
    gradient: 'from-orange-500 to-amber-600',
    techRadarRing: 'adopt',
    techRadarReason: 'Идеально для контент-сайтов, Zero JS default',
    designRating: 9,
    integrationRating: 9,
    learningRating: 8,
    documentationRating: 9,
    communityRating: 7,
    performanceRating: 10,
    githubStars: '48K',
    npmDownloads: '600K/нед',
    bundleSize: '0 KB',
    bundleSizeBytes: 0,
    trend: 'up',
    difficulty: 1,
    recommended: true,
    beginnerFriendly: true,
    maintained: true,
    openSource: true,
  },
  // Styling
  {
    id: 'tailwind',
    type: 'technology',
    name: 'Tailwind CSS',
    description: 'Utility-first CSS фреймворк. Самый популярный подход к стилизации в современном вебе.',
    attributes: JSON.stringify({
      url: 'https://tailwindcss.com/',
      version: '4',
      company: 'Tailwind Labs',
      browserSupport: ['All Browsers'],
      nodeVersion: '>=16',
      typescript: 'native',
      bestFor: ['Любой проект', 'Быстрая разработка'],
      pros: ['Utility-first', 'JIT', 'Отличная документация'],
      cons: ['Много классов в HTML'],
    }),
    tags: JSON.stringify(['css', 'styling', 'utility-first', 'jit', 'responsive']),
    source: 'UI Radar',
    popularity: 96,
    gradient: 'from-sky-400 to-cyan-600',
    techRadarRing: 'adopt',
    techRadarReason: 'Стандарт для стилизации, JIT компилятор, отличная DX',
    designRating: 9,
    integrationRating: 10,
    learningRating: 7,
    documentationRating: 10,
    communityRating: 10,
    performanceRating: 10,
    githubStars: '82K',
    npmDownloads: '15M/нед',
    bundleSize: '10-30 KB',
    bundleSizeBytes: 15000,
    trend: 'up',
    difficulty: 2,
    recommended: true,
    beginnerFriendly: true,
    maintained: true,
    openSource: true,
  },
  // Animation
  {
    id: 'framer-motion',
    type: 'technology',
    name: 'Framer Motion',
    description: 'Анимации для React. Декларативный API, gestures, layout animations.',
    attributes: JSON.stringify({
      url: 'https://www.framer.com/motion',
      version: '12',
      company: 'Framer',
      browserSupport: ['Chrome', 'Firefox', 'Safari', 'Edge'],
      nodeVersion: '>=16',
      typescript: 'native',
      bestFor: ['React анимации', 'Page transitions'],
      pros: ['Declarative API', 'Gestures', 'Layout animations'],
      cons: ['Только React'],
    }),
    tags: JSON.stringify(['animation', 'gestures', 'declarative', 'motion', 'transitions', 'react']),
    source: 'Package.json',
    popularity: 88,
    gradient: 'from-purple-500 to-pink-500',
    techRadarRing: 'trial',
    techRadarReason: 'Отлично для React, но есть альтернативы (CSS, GSAP)',
    designRating: 9,
    integrationRating: 9,
    learningRating: 7,
    documentationRating: 9,
    communityRating: 9,
    performanceRating: 8,
    githubStars: '23K',
    npmDownloads: '6M/нед',
    bundleSize: '25 KB',
    bundleSizeBytes: 25000,
    trend: 'up',
    difficulty: 2,
    recommended: true,
    beginnerFriendly: true,
    maintained: true,
    openSource: true,
  },
  // TypeScript
  {
    id: 'typescript',
    type: 'technology',
    name: 'TypeScript',
    description: 'JavaScript с типами для разработки масштабируемых приложений.',
    attributes: JSON.stringify({
      url: 'https://www.typescriptlang.org',
      version: '5',
      company: 'Microsoft',
      bestFor: ['Любой проект', 'Type safety'],
      pros: ['Типобезопасность', 'Лучший DX', 'Меньше багов'],
      cons: ['Кривая обучения'],
    }),
    tags: JSON.stringify(['typescript', 'types', 'javascript', 'static-typing']),
    source: 'Package.json',
    popularity: 95,
    gradient: 'from-blue-600 to-blue-800',
    techRadarRing: 'adopt',
    techRadarReason: 'Стандарт для современных проектов',
    designRating: 8,
    integrationRating: 10,
    learningRating: 7,
    documentationRating: 10,
    communityRating: 10,
    performanceRating: 9,
    githubStars: '100K',
    npmDownloads: '50M/нед',
    bundleSize: 'N/A',
    bundleSizeBytes: 0,
    trend: 'up',
    difficulty: 2,
    recommended: true,
    beginnerFriendly: true,
    maintained: true,
    openSource: true,
  },
  // Principles
  {
    id: 'atomic-design',
    type: 'principle',
    name: 'Атомарный дизайн',
    description: 'Методология, предполагающая создание систем из атомов (базовые теги), молекул (составные элементы) и организмов (крупные блоки). Разработана Брэдом Фростом для создания масштабируемых и согласованных интерфейсов.',
    attributes: JSON.stringify({
      author: 'Brad Frost',
      url: 'http://bradfrost.com/blog/post/atomic-web-design/',
      levels: 5,
      hierarchy: ['atoms', 'molecules', 'organisms', 'templates', 'pages'],
      features: ['Атомы', 'Молекулы', 'Организмы', 'Шаблоны', 'Страницы'],
      year: 2013,
      benefits: ['scalability', 'consistency', 'reusability'],
    }),
    tags: JSON.stringify(['design-systems', 'architecture', 'component-hierarchy', 'brad-frost', 'modular', 'methodology', 'scalability', 'structure', 'components']),
    source: 'design-systems-overview',
    popularity: 90,
    gradient: 'from-blue-500 to-purple-500',
    techRadarRing: 'adopt',
    techRadarReason: 'Фундаментальная методология для дизайн-систем',
    designRating: 9,
    integrationRating: 8,
    learningRating: 8,
    documentationRating: 9,
    communityRating: 9,
    performanceRating: 8,
    githubStars: 'N/A',
    npmDownloads: 'N/A',
    bundleSize: 'N/A',
    bundleSizeBytes: 0,
    trend: 'stable',
    difficulty: 3,
    recommended: true,
    beginnerFriendly: true,
    maintained: true,
    openSource: true,
  },
  {
    id: 'design-tokens',
    type: 'principle',
    name: 'Design Tokens',
    description: 'Визуальные атомы дизайн-системы — именованные сущности, хранящие атрибуты визуального дизайна. Обеспечивают согласованность на всех платформах и упрощают обновление стилей.',
    attributes: JSON.stringify({
      standard: 'Design Tokens Community Group',
      format: 'JSON',
      tooling: ['style-dictionary', 'figma-tokens', 'tokens-studio'],
      token_types: ['color', 'typography', 'spacing', 'border-radius', 'shadows'],
      features: ['Цвета', 'Типографика', 'Отступы', 'Тени и радиусы'],
      categories: ['colors', 'typography', 'spacing', 'shadows', 'radii'],
      tools: ['Style Dictionary', 'Theo', 'Figma Tokens'],
    }),
    tags: JSON.stringify(['cross-platform', 'variables', 'consistency', 'multi-platform', 'automation', 'theming', 'tokens']),
    source: 'design-systems-overview',
    popularity: 88,
    gradient: 'from-purple-500 to-indigo-600',
    techRadarRing: 'adopt',
    techRadarReason: 'Стандарт для дизайн-систем',
    designRating: 9,
    integrationRating: 9,
    learningRating: 7,
    documentationRating: 8,
    communityRating: 8,
    performanceRating: 10,
    githubStars: 'N/A',
    npmDownloads: 'N/A',
    bundleSize: 'N/A',
    bundleSizeBytes: 0,
    trend: 'up',
    difficulty: 3,
    recommended: true,
    beginnerFriendly: true,
    maintained: true,
    openSource: true,
  },
  {
    id: 'accessibility',
    type: 'principle',
    name: 'Доступность (Accessibility)',
    description: 'Принцип, заложенный в основу многих систем, чтобы продуктами могли пользоваться люди с разными возможностями. Включает соответствие стандартам WCAG и инклюзивный дизайн для всех пользователей.',
    attributes: JSON.stringify({
      wcag_version: '2.1',
      features: ['Соответствие WCAG', 'Поддержка скринридеров', 'Контраст цветов', 'Навигация с клавиатуры'],
      standard: 'WCAG 2.1',
      levels: ['A', 'AA', 'AAA'],
      aspects: ['screen-readers', 'color-contrast', 'keyboard-nav', 'focus-management'],
      tools: ['axe', 'WAVE', 'Lighthouse'],
      category: 'fundamental',
      importance: 'high',
    }),
    tags: JSON.stringify(['screen-readers', 'wcag', 'universal-design', 'keyboard', 'a11y', 'inclusive']),
    source: 'DesignSystems from Figma',
    popularity: 95,
    gradient: 'from-green-500 to-teal-600',
    techRadarRing: 'adopt',
    techRadarReason: 'Критически важно для современных продуктов',
    designRating: 10,
    integrationRating: 9,
    learningRating: 7,
    documentationRating: 9,
    communityRating: 9,
    performanceRating: 8,
    githubStars: 'N/A',
    npmDownloads: 'N/A',
    bundleSize: 'N/A',
    bundleSizeBytes: 0,
    trend: 'up',
    difficulty: 3,
    recommended: true,
    beginnerFriendly: true,
    maintained: true,
    openSource: true,
  },
]

// Learning steps data
export const learningStepsData = [
  { id: 'step-1', step: 1, name: 'HTML/CSS/JS', description: 'База веб-разработки. Фундамент для любого фронтенд-разработчика.', time: '2-3 мес', difficulty: 1, order: 1 },
  { id: 'step-2', step: 2, name: 'Фреймворк', description: 'React или Vue. Выбор основного инструмента для разработки.', time: '1-2 мес', difficulty: 2, order: 2, options: JSON.stringify(['React', 'Vue']) },
  { id: 'step-3', step: 3, name: 'TypeScript', description: 'Типобезопасность. Повышение качества кода и DX.', time: '2-4 нед', difficulty: 2, order: 3 },
  { id: 'step-4', step: 4, name: 'Стилизация', description: 'Tailwind CSS. Современный подход к CSS.', time: '1-2 нед', difficulty: 1, order: 4, recommended: 'Tailwind CSS' },
  { id: 'step-5', step: 5, name: 'UI Компоненты', description: 'Shadcn UI/DaisyUI. Готовые компоненты для быстрой разработки.', time: '1-2 нед', difficulty: 1, order: 5, options: JSON.stringify(['Shadcn UI', 'DaisyUI']) },
  { id: 'step-6', step: 6, name: 'Мета-фреймворк', description: 'Next.js/Nuxt. SSR/SSG и production-ready приложения.', time: '1-2 мес', difficulty: 3, order: 6, options: JSON.stringify(['Next.js', 'Nuxt']) },
]

// Courses data for Academy
export const coursesData = [
  { id: 'course-1', name: 'Основы дизайн-систем', description: 'Базовый курс по дизайн-системам: что это, зачем нужны, из чего состоят', icon: 'BookOpen', lessons: 8, category: 'basics', order: 1 },
  { id: 'course-2', name: 'Цвет и Типографика', description: 'Курс по визуальным аспектам: цветовые палитры, типографические шкалы, доступность', icon: 'Palette', lessons: 12, category: 'visual', order: 2 },
  { id: 'course-3', name: 'Анимации и переходы', description: 'Курс по анимациям интерфейсов: тайминги, easing, микро-взаимодействия', icon: 'Zap', lessons: 6, category: 'animation', order: 3 },
  { id: 'course-4', name: 'Технологии и инструменты', description: 'Курс по технической реализации: фреймворки, библиотеки, инструменты разработки', icon: 'Code2', lessons: 10, category: 'technical', order: 4 },
  { id: 'course-5', name: 'Компоненты и паттерны', description: 'Атомарный дизайн, компонентный подход, UI паттерны', icon: 'Layers', lessons: 14, category: 'components', order: 5 },
  { id: 'course-6', name: 'Документация и поддержка', description: 'Как документировать дизайн-систему и поддерживать её развитие', icon: 'FileText', lessons: 8, category: 'process', order: 6 },
]

// Tech stacks data for recommendations
export const techStacksData = [
  {
    id: 'stack-react',
    name: 'React Starter',
    description: 'Идеальный стек для начинающих. React + Tailwind + Shadcn UI + Lucide.',
    difficulty: 'easy',
    stack: JSON.stringify(['react', 'tailwind', 'shadcn-ui', 'lucide']),
    useCase: 'Первое веб-приложение, портфолио',
    pros: JSON.stringify(['Много туториалов', 'Быстрая разработка', 'Полный контроль кода']),
    timeToLearn: '1-2 месяца',
    why: JSON.stringify({
      synergy: 'React + Tailwind — стандарт индустрии. Shadcn UI добавляет готовые компоненты БЕЗ зависимости от npm пакета.',
      problem: 'Решает проблему "с чего начать" — минимум решений, максимум результата.',
      alternative: 'НЕ выбирай, если нужен SSR/SEO (лучше Next.js) или если хочешь Vue.',
    }),
    toolsExplanation: JSON.stringify({
      framework: 'React — самая популярная библиотека. Максимальное количество вакансий, туториалов.',
      styling: 'Tailwind CSS — utility-first подход. Классы прямо в JSX.',
      components: 'shadcn-ui — НЕ npm пакет! Код копируется в твой проект. Полный контроль.',
      icons: 'Lucide — 1000+ иконок, tree-shakeable.',
    }),
  },
  {
    id: 'stack-nextjs',
    name: 'Next.js Production',
    description: 'Готовый к продакшену стек с SSR. Next.js + Tailwind + Shadcn-ui + Framer Motion + Lucide.',
    difficulty: 'medium',
    stack: JSON.stringify(['nextjs', 'tailwind', 'shadcn-ui', 'framer-motion', 'lucide']),
    useCase: 'SSR сайты, e-commerce, корпоративные сайты',
    pros: JSON.stringify(['SEO оптимизация', 'SSR/SSG из коробки', 'API Routes']),
    timeToLearn: '2-3 месяца',
    why: JSON.stringify({
      synergy: 'Next.js + Shadcn UI — официальный стек от Vercel.',
      problem: 'Решает SEO проблему SPA — серверный рендеринг для поисковиков.',
      alternative: 'НЕ выбирай для простых SPA или если хостинг не Vercel.',
    }),
    toolsExplanation: JSON.stringify({
      framework: 'Next.js — React фреймворк от Vercel. SSR/SSG из коробки = SEO для Google.',
      styling: 'Tailwind CSS — официально рекомендован Vercel.',
      components: 'Shadcn UI — специальный CLI для Next.js.',
      animation: 'Framer Motion — декларативные анимации.',
      icons: 'Lucide — минимальный bundle, tree-shakeable.',
    }),
  },
  {
    id: 'stack-svelte',
    name: 'Svelte Minimal',
    description: 'Минимальный bundle и максимальная скорость. SvelteKit + Tailwind + DaisyUI.',
    difficulty: 'easy',
    stack: JSON.stringify(['sveltekit', 'tailwind', 'daisyui']),
    useCase: 'Быстрые сайты, landing pages, виджеты',
    pros: JSON.stringify(['Сверхмалый bundle', 'Простота', 'Нет Virtual DOM']),
    timeToLearn: '1 месяц',
    why: JSON.stringify({
      synergy: 'Svelte компилируется в чистый JS — нет Virtual DOM overhead.',
      problem: 'Идеально для landing pages, где каждая миллисекунда загрузки = деньги.',
      alternative: 'НЕ выбирай для больших SPA (экосистема меньше React).',
    }),
    toolsExplanation: JSON.stringify({
      framework: 'SvelteKit — компилируется в чистый JavaScript. Bundle в 10-50 раз меньше React.',
      styling: 'Tailwind CSS — работает через svelte-preprocess.',
      components: 'DaisyUI — идеальная пара для Svelte. Чистый CSS.',
    }),
  },
  {
    id: 'stack-content',
    name: 'Content Site',
    description: 'Идеально для блогов и документации. Astro + Tailwind + Lucide.',
    difficulty: 'easy',
    stack: JSON.stringify(['astro', 'tailwind', 'lucide']),
    useCase: 'Блоги, документация, портфолио, маркетинговые сайты',
    pros: JSON.stringify(['Zero JS default', 'Очень быстрый', 'SEO идеально']),
    timeToLearn: '2-3 недели',
    why: JSON.stringify({
      synergy: 'Astro — контент-first фреймворк. По умолчанию Zero JavaScript на клиенте.',
      problem: 'Блоги, документация, портфолио — где контент важнее интерактивности.',
      alternative: 'НЕ выбирай для SPA приложений или если нужна сложная интерактивность.',
    }),
    toolsExplanation: JSON.stringify({
      framework: 'Astro — Content-first фреймворк. Islands Architecture = JS только для интерактивных частей.',
      styling: 'Tailwind CSS — официальный плагин @astrojs/tailwind.',
      icons: 'Lucide — SVG иконки без фреймворк-зависимости.',
    }),
  },
  {
    id: 'stack-vue',
    name: 'Vue Starter',
    description: 'Vue.js стек для новичков. Vue + Tailwind + DaisyUI + Heroicons.',
    difficulty: 'easy',
    stack: JSON.stringify(['vue', 'tailwind', 'daisyui', 'heroicons']),
    useCase: 'SPA приложения, быстрые прототипы',
    pros: JSON.stringify(['Простая документация', 'Низкий порог входа', 'SFC']),
    timeToLearn: '1-2 месяца',
    why: JSON.stringify({
      synergy: 'Vue — самый простой для изучения фреймворк. DaisyUI — компоненты БЕЗ JavaScript.',
      problem: 'DaisyUI решает проблему "нужно писать много CSS" — 30+ готовых тем.',
      alternative: 'НЕ выбирай, если планируешь работать в enterprise (там чаще React).',
    }),
    toolsExplanation: JSON.stringify({
      framework: 'Vue.js — самый простой порог входа. Single File Components = HTML + JS + CSS в одном файле.',
      styling: 'Tailwind CSS — универсальный выбор.',
      components: 'DaisyUI — 30+ готовых тем, чистый CSS БЕЗ JavaScript!',
      icons: 'Heroicons — от Tailwind Labs. 3 стиля.',
    }),
  },
]

// Tech radar data for interactive guide
export const techRadarData = {
  adopt: {
    color: '#10b981',
    level: 1,
    technologies: [
      { id: 'react', name: 'React', reason: 'Стандарт индустрии, огромная экосистема, максимум вакансий', popularity: 98, bundleSize: '42 KB' },
      { id: 'vue', name: 'Vue.js', reason: 'Отличная документация, низкий порог входа, растущее сообщество', popularity: 95, bundleSize: '34 KB' },
      { id: 'nextjs', name: 'Next.js', reason: 'Лучший выбор для SSR/SSG, официальная рекомендация Vercel', popularity: 94, bundleSize: '85 KB' },
      { id: 'tailwind', name: 'Tailwind CSS', reason: 'Стандарт для стилизации, JIT компилятор, отличная DX', popularity: 96, bundleSize: '10-30 KB' },
      { id: 'shadcn-ui', name: 'shadcn/ui', reason: 'Полный контроль кода, не npm пакет, красивый дизайн', popularity: 90, bundleSize: 'По компонентам' },
      { id: 'lucide', name: 'Lucide', reason: 'Tree-shakeable, 1000+ иконок, активное развитие', popularity: 95, bundleSize: 'Tree-shakeable' },
      { id: 'nuxt', name: 'Nuxt', reason: 'Зрелый Vue фреймворк, отличная документация', popularity: 91, bundleSize: '50 KB' },
      { id: 'astro', name: 'Astro', reason: 'Идеально для контент-сайтов, Zero JS default', popularity: 98, bundleSize: '0 KB' },
    ],
  },
  trial: {
    color: '#3b82f6',
    level: 2,
    technologies: [
      { id: 'sveltekit', name: 'SvelteKit', reason: 'Очень быстрый, маленький bundle, но молодая экосистема', popularity: 96, bundleSize: '10 KB' },
      { id: 'svelte', name: 'Svelte', reason: 'Инновационный подход, но меньше вакансий', popularity: 97, bundleSize: '1.6 KB' },
      { id: 'framer-motion', name: 'Framer Motion', reason: 'Отлично для React, но есть альтернативы (CSS, GSAP)', popularity: 88, bundleSize: '25 KB' },
      { id: 'daisyui', name: 'DaisyUI', reason: 'Отлично для прототипов, но ограниченная кастомизация', popularity: 92, bundleSize: '30 KB' },
      { id: 'mantine', name: 'Mantine', reason: '120+ компонентов, но большой bundle', popularity: 92, bundleSize: '200+ KB' },
      { id: 'chakra', name: 'Chakra UI', reason: 'Простота использования, но меньше компонентов', popularity: 88, bundleSize: '180 KB' },
    ],
  },
  assess: {
    color: '#f59e0b',
    level: 3,
    technologies: [
      { id: 'solid', name: 'Solid.js', reason: 'Высокая производительность, но маленькая экосистема', popularity: 89, bundleSize: '7 KB' },
      { id: 'radix', name: 'Radix UI', reason: 'Headless, но нужны свои стили (сложнее для новичков)', popularity: 95, bundleSize: '5-15 KB' },
      { id: 'heroicons', name: 'Heroicons', reason: 'От Tailwind Labs, но меньше иконок чем у Lucide', popularity: 94, bundleSize: 'Tree-shakeable' },
      { id: 'gsap', name: 'GSAP', reason: 'Мощный, но сложный для изучения и платный для коммерции', popularity: 82, bundleSize: '45 KB' },
    ],
  },
  hold: {
    color: '#ef4444',
    level: 4,
    technologies: [
      { id: 'angular', name: 'Angular', reason: 'Высокая сложность, большой bundle, специфичный рынок', popularity: 72, bundleSize: '500+ KB' },
      { id: 'mui', name: 'Material-UI', reason: 'Тяжелый, Material Design не для всех, есть легче альтернативы', popularity: 78, bundleSize: '300+ KB' },
    ],
  },
}
